#!/bin/bash
## api
## version 0.0.1 - initial
##################################################
request() {
  local body=""
  local signature=$( echo -n "${timestamp}${method}${request_path}${body}" | openssl dgst -sha256 -hmac "${coinbase_api_secret}" )
  curl "https://api.coinbase.com${request_path}" \
  -H "CB-ACCESS-KEY: ${coinbase_api_key}" \
  -H "CB-ACCESS-SIGN: ${signature}" \
  -H "CB-ACCESS-TIMESTAMP: ${timestamp}" \
  -H "CB-VERSION: 2021-03-20" \
  --silent
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################