#!/bin/bash
## clipboy-act
## - do things with clipboard content
## version 0.0.1 - initial
##################################################
clipboy-act() {
  clipboy-say "Me's doing it!"
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Thu, 08 Nov 2018 12:51:06 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
