#!/bin/bash
## clipboy
## - reads from clipboard and does things
## version 0.0.1 - initial
##################################################
. ${SH2}/error.sh		# error handling
error "true"			# show errors
. ${SH2}/cecho.sh		# colored echo
. ${SH2}/aliases/commands.sh	# commands
##################################################
generate-temp() { ${SH2}/generate-temp.sh ${@} ; }
##################################################
_cleanup() {
  cecho yellow $( rm -rvf ${temp}-* )
}
temp= 
initialize() {
 temp=$( 
  generate-temp 
 )
 touch "${temp}-test"
}
clipboy-say() {
 cecho green "${@}"
}
clipboy-run() {
 clipboy-say "Hey!"
 touch "${temp}-clipboard"
 while [ ! ]
 do
  cat /dev/clipboard > ${temp}-infile
  diff ${temp}-{clipboard,infile} || true
  ################################################
  ## =todo=
  ## + add payload here
  ################################################
  #read
  break
  ################################################
 done
 clipboy-say "Bye!"
}
clipboy() {
 initialize
 commands
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
clipboy ${@}
##################################################
## generated by create-stub2.sh v0.1.1
## on Thu, 08 Nov 2018 12:51:06 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
