#!/bin/bash
## clipboy-dialog-sample
## - override things clipboy says
## version 0.0.1 - initial
##################################################
# =functions=
# + clipboy-dialog-hi
# + clipboy-dialog-bye
# + clipboy-dialog-stretch
# + clipboy-dialog-hungry
# + clipboy-dialog-delicious
# + clipboy-dialog-thinking
# + clipboy-dialog-sleepy
# =directions=
# 1. `cp -vf clipboy-dialog-custom{-sample,}.sh`
# 1. customize through clipboy-dialog-custom.sh
# =example=
# - say hi in Japanese
clipboy-dialog-hi() {
 echo "こんにちは！"
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Thu, 08 Nov 2018 12:51:06 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
