#!/bin/bash
## clipboy-dialog
## - things clipboy says
## version 0.0.1 - initial
##################################################
clipboy-dialog-hi() {
 echo "Hey!"
}
clipboy-dialog-bye() {
 echo "Bye!"
}
clipboy-dialog-stretch() {
 echo "Me's stretch first.."
}
clipboy-dialog-hungry() {
 echo "Me's hungry ..."
}
clipboy-dialog-delicious() {
 echo "Um.. Um.. Yummy!"
}
clipboy-dialog-thinking() {
 echo "Me's thinking..."
}
clipboy-dialog-sleepy() {
 echo "Me's sleepy..."
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Thu, 08 Nov 2018 12:51:06 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
