#!/bin/bash
## clipboy-make-subcommand
## version 0.0.2 - shellcheck
##################################################
clipboy-make-subcommand() { { local function_name ; function_name="${1}" ; }
  # shellcheck disable=SC2154
  function-body-script() {
    cat << EOF
  . \$( dirname \${0} )/scripts/$( date +%y%m%d )-${program}.sh \${@}
EOF

  }
  function-body-true() {
    cat << EOF
  true
EOF
  }
  # shellcheck disable=SC2128
  function-body() {
    test ! -f "${scripts}/$( date +%y%m%d )-${program}.sh"  || { 
      echo "using script" 1>&2
      "${FUNCNAME}-script"
      return
    }
    cecho "using true" 1>&2
    "${FUNCNAME}-true"
  }
  test "${function_name}" || {
    clipboy-say "What subcommand Me makes?" 
    read -r candidate_command
    function_name=${candidate_command}
  }
  test ! "${function_name}" || {
    # shellcheck disable=SC2086
    test -f "$( dirname ${0} )/${function_name}.sh" || {
      clipboy-say "Me makes ${function_name} subcommand"
      {
        {
          create-stub-generate-stub-head() { 
	    cat << EOF
#!/bin/bash
## ${program}
## version 0.0.1 - initial
EOF
          }
	  create-stub-generate-stub-entry() {
            cat << EOF
##################################################
clipboy-${program}() { 
$( function-body )
}
##################################################
## generated by $( basename ${0} ) v$( grep -e 'version' ${0} | head -n  1 | cut '-f3' '-d ' )
## on $( date --rfc-2822 )
## see <https://github.com/temptemp3/sh2>
##################################################
EOF
          }
	  declare -xf create-stub-generate-stub-head
	  declare -xf create-stub-generate-stub-entry
	  declare -xf function-body
	  declare -xf function-body-script
	  declare -xf function-body-true
	  declare -x scripts
	  scripts="$( dirname ${0} )/scripts"
          create-stub2 ${function_name} 
        } | tee "$( dirname ${0} )/commands/$( date +%y%m%d )-clipboy-${function_name}.sh"
      } &>/dev/null
    }
  }  
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 26 Feb 2020 08:48:58 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
