#!/bin/bash
## store-set
## version 0.0.1 - initial
##################################################
clipboy-store-set() { 
  . $( dirname ${0} )/scripts/200305-store-set.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 05 Mar 2020 21:06:41 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
