#!/bin/bash
## store
## version 0.0.2 - shellcheck
##################################################
command-name-third-person-present() {
  echo "${command_name}s"
}
clipboy-store-default() {
  clipboy-say "Me $( command-name-third-person-present )"
}
clipboy-store-help() { 
  clipboy-store() {
    commands
  }
  unset -f "clipboy-${command_name}-help"
  unset -f "clipboy-${command_name}-default"
  "clipboy-${command_name}"
}
clipboy-store() { { local command_type ; command_type=$( echo "${1}" | cut '-d:' '-f2' ) ; }
 local command_name
  command_name="store"
  # shellcheck disable=SC2128
  case $( declare -f "${FUNCNAME}-${command_type}" ) in
   "") {
     "${FUNCNAME}-default"
   } ;;
   *) {
     "${FUNCNAME}-${command_type}" "${@:2}"
   } ;;
  esac
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 05 Mar 2020 10:38:31 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
