#!/bin/bash
## store-list
## version 0.0.1 - initial
##################################################
clipboy-store-list() { 
  . $( dirname ${0} )/scripts/200305-store-list.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 05 Mar 2020 21:33:18 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
