#!/bin/bash
## store-get
## version 0.0.2 - shellcheck
##################################################
clipboy-store-get() { 
  # shellcheck disable=SC1091,SC2086
  . "$( dirname ${0} )/scripts/200305-store-get.sh" "${@}"
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 05 Mar 2020 21:15:02 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
