#!/bin/bash
## make-script
## version 0.0.1 - initial
##################################################
clipboy-make-script() { { local function_name ; function_name="${1}" ; }
  test "${function_name}" || {
    clipboy-say "What script Me makes?" 
    read candidate_command
    function_name=${candidate_command}
  }
  test ! "${function_name}" || {
    test -f "$( dirname ${0} )/${function_name}.sh" || {
      clipboy-say "Me makes ${function_name} script"
      {
        {
          create-stub-generate-stub-head() { 
	    cat << EOF
#!/bin/bash
## ${program}
## version 0.0.1 - initial
EOF
          }
	  create-stub-generate-stub-entry() {
            cat << EOF
##################################################
_${program}() { 
  true
}
##################################################
_${program} \${@}
##################################################
## generated by $( basename ${0} ) v$( grep -e 'version' ${0} | head -n  1 | cut '-f3' '-d ' )
## on $( date --rfc-2822 )
## see <https://github.com/temptemp3/sh2>
##################################################
EOF
          }
	  declare -xf create-stub-generate-stub-head
	  declare -xf create-stub-generate-stub-entry
	  test -d "$( dirname ${0} )/scripts" || {
	    cecho yellow $( mkdir -pv ${_} )
          }
          create-stub2 ${function_name} 
        } | tee $( dirname ${0} )/scripts/$( date +%y%m%d )-${function_name}.sh
      } &>/dev/null
    }
  } 
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 04 Mar 2020 15:47:36 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
