#!/bin/bash
## install
## version 0.0.1 - initial
##################################################
clipboy-install() { 
  . $( dirname ${0} )/scripts/201012-install.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 12 Oct 2020 23:19:02 +1100
## see <https://github.com/temptemp3/sh2>
##################################################
