#!/bin/bash
## list
## version 0.0.1 - initial
##################################################
list() {
  true
}
get-value() { 
  true
}
interface() { { local key ; key="${1}" ; }
  init-store-silent
  test "$( store get ${key} )" || {
    store set ${key} "$( get-value )"
    store persist
  }
  store get ${key} | inflate
}
inflate() {
  xxd -ps -r | gzip -d
}
deflate() {
  gzip -9 | xxd -ps | tr -d '\n'
}
command-name-third-person-present() {
  echo "${command_name}s"
}
clipboy-list-default() {
  clipboy-say "Me $( command-name-third-person-present )"
}
clipboy-list-help() { 
  clipboy-list() {
    commands
  }
  unset -f clipboy-${command_name}-help
  unset -f clipboy-${command_name}-default
  clipboy-${command_name}
}
clipboy-list() { { local command_type ; command_type="$( echo ${1} | cut '-d:' '-f2' )" ; }
 local command_name
  command_name="list"
  case "$( declare -f ${FUNCNAME}-${command_type} )" in
   "") {
     ${FUNCNAME}-default
   } ;;
   *) {
     ${FUNCNAME}-${command_type} ${@:2}
   } ;;
  esac
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
