#!/bin/bash
## list-funded-account-prices
## version 0.0.1 - initial
##################################################
clipboy-list-funded-account-prices() { 
  . $( dirname ${0} )/scripts/210419-list-funded-account-prices.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
