#!/bin/bash
## watch-price
## version 0.0.1 - initial
##################################################
clipboy-watch-price() { 
  . $( dirname ${0} )/scripts/210405-watch-price.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
