#!/bin/bash
## list-funded-accounts
## version 0.0.1 - initial
##################################################
clipboy-list-funded-accounts() { 
  . $( dirname ${0} )/scripts/210413-list-funded-accounts.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
