#!/bin/bash
## portfolio-assets
## version 0.0.1 - initial
##################################################
clipboy-portfolio-assets() { 
  . $( dirname ${0} )/scripts/210413-portfolio-assets.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
