#!/bin/bash
## portfolio
## version 0.0.1 - initial
##################################################
sum() {
  gawk '{sum+=$(1)} END {print sum}' -
}
get-balance() {
  echo "${balance}"
}
get-peg-diff() {
  echo "${peg_diff}"
}
get() {
  commands
}
foreach-funded-account() { { local function_name ; function_name="${1}" ; }
  coinboy list:funded-accounts | while read -r code amount peg price balance peg_diff
  do
   "${function_name}"
  done
}
command-name-third-person-present() {
  echo "${command_name}s"
}
clipboy-portfolio-default() {
  clipboy-say "Me $( command-name-third-person-present )"
}
clipboy-portfolio-help() { 
  clipboy-portfolio() {
    commands
  }
  unset -f clipboy-${command_name}-help
  unset -f clipboy-${command_name}-default
  clipboy-${command_name}
}
clipboy-portfolio() { { local command_type ; command_type="$( echo ${1} | cut '-d:' '-f2' )" ; }
 local command_name
  command_name="portfolio"
  case "$( declare -f ${FUNCNAME}-${command_type} )" in
   "") {
     ${FUNCNAME}-default
   } ;;
   *) {
     ${FUNCNAME}-${command_type} ${@:2}
   } ;;
  esac
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
