#!/bin/bash
## prices
## version 0.0.2 - add functions
##################################################
command-name-third-person-present() {
  echo "${command_name}s"
}
clipboy-prices-default() {
  clipboy-say "Me $( command-name-third-person-present )"
}
clipboy-prices-help() { 
  clipboy-prices() {
    commands
  }
  unset -f clipboy-${command_name}-help
  unset -f clipboy-${command_name}-default
  clipboy-${command_name}
}
get-price() {
  local price=$( request | jq -r '.data.amount' )
  local decimal="${price//*./}"
  test ! ${#decimal} -lt ${SCALE:-2} || {
    local i
    for i in $( seq $(( ${SCALE} - ${#decimal} )) )
    do
     price="${price}0"
    done
  }
  echo -n "${price}"
}
_prices-type() { { local type ; type="${2:-spot}" ; }
  local timestamp=$( date +%s )
  local method="GET" 
  local request_path="/v2/prices/${currency_pair}/${type}" ;
  local price=$( get-price )
  echo -n "${price}"
}
clipboy-prices() { { local command_type ; command_type="$( echo ${1} | cut '-d:' '-f2' )" ; }
  local command_name
  command_name="prices"
  case "$( declare -f ${FUNCNAME}-${command_type} )" in
   "") {
     ${FUNCNAME}-default
   } ;;
   *) {
     ${FUNCNAME}-${command_type} ${@:2}
   } ;;
  esac
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
