#!/bin/bash
## portfolio-peg-total
## version 0.0.1 - initial
##################################################
clipboy-portfolio-peg-total() { 
  . $( dirname ${0} )/scripts/210421-portfolio-peg-total.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
