#!/bin/bash
## transactions-show
## version 0.0.1 - initial
##################################################
clipboy-transactions-show() { 
  . $( dirname ${0} )/scripts/210404-transactions-show.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
