#!/bin/bash
## portfolio-balance
## version 0.0.1 - initial
##################################################
clipboy-portfolio-balance() { 
  . $( dirname ${0} )/scripts/210413-portfolio-balance.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
