#!/bin/bash
## watch-crypto
## version 0.0.1 - initial
##################################################
clipboy-watch-crypto() { 
  . $( dirname ${0} )/scripts/210407-watch-crypto.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
