#!/bin/bash
## buys-list
## version 0.0.1 - initial
##################################################
clipboy-buys-list() { 
  . $( dirname ${0} )/scripts/210415-buys-list.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
