#!/bin/bash
## store-purge
## version 0.0.1 - initial
##################################################
clipboy-store-purge() { 
  . $( dirname ${0} )/scripts/210419-store-purge.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
