#!/bin/bash
## store-env
## version 0.0.1 - initial
##################################################
clipboy-store-env() { 
  . $( dirname ${0} )/scripts/210416-store-env.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
