#!/bin/bash
## watch
## version 0.0.2 - add today
##################################################
command-name-third-person-present() {
  echo "${command_name}s"
}
clipboy-watch-default() {
  clipboy-say "Me $( command-name-third-person-present )"
}
clipboy-watch-help() { 
  clipboy-watch() {
    commands
  }
  unset -f clipboy-${command_name}-help
  unset -f clipboy-${command_name}-default
  clipboy-${command_name}
}
clipboy-watch() { { local command_type ; command_type="$( echo ${1} | cut '-d:' '-f2' )" ; }
  local command_name
  local -r today=$( date +%y%m%d )
  command_name="watch"
  case "$( declare -f ${FUNCNAME}-${command_type} )" in
   "") {
     ${FUNCNAME}-default
   } ;;
   *) {
     ${FUNCNAME}-${command_type} ${@:2}
   } ;;
  esac
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
