#!/bin/bash
## prices-buy
## version 0.0.1 - initial
##################################################
clipboy-prices-buy() { 
  . $( dirname ${0} )/scripts/210405-prices-buy.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
