#!/bin/bash
## run-example-001-bash-declare-intenger-assignment
## version 0.0.1 - initial
##################################################
clipboy-run-example-001-bash-declare-intenger-assignment() { 
  . $( dirname ${0} )/scripts/210513-run-example-001-bash-declare-intenger-assignment.sh ${@}
}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
