#!/bin/bash
## store-get
## version 0.0.2 - shellcheck
##################################################
# shellcheck disable=SC1091
 . "${SH2}/store.sh"
_store-get() { { local key ; key="${1}" ; local value ; value="${2}" ; }
  init-store-silent
  store get "${key}" "${value}"
}
##################################################
_store-get "${@}"
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 05 Mar 2020 21:14:50 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
