#!/bin/bash
## store-list
## version 0.0.2 - w/o xargs
##################################################
_store-list() { 
  init-store-silent
  local key
  for key in ${!store[@]}
  do
   echo ${key}: ${store[${key}]}
  done
}
##################################################
_store-list ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on Thu, 05 Mar 2020 21:33:08 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
