#!/bin/bash
## install
## version 0.0.2 - shellcheck
##################################################
_install() { 
  test -f "clipboy.sh" || { true ; return ; }
  {
    cat << EOF
$( basename "$( pwd )" )() {
  bash $( pwd )/clipboy.sh \${@}
}
EOF
  } >> ~/.bashrc
}
##################################################
_install
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 12 Oct 2020 23:18:51 +1100
## see <https://github.com/temptemp3/sh2>
##################################################
