#!/bin/bash
## prices-sell
## version 0.0.2 - minimal
##################################################
_prices-sell() { { local currency_pair ; currency_pair="${1:-BTC-USD}" ; }
  _prices-type sell
}
##################################################
_prices-sell ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
