#!/bin/bash
## portfolio-balance
## version 0.0.1 - initial
##################################################
_portfolio-balance() { 
  foreach-funded-account get-balance | sum
}
##################################################
_portfolio-balance ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
