#!/bin/bash
## list-funded-account-balances
## version 0.0.1 - initial
##################################################
list() {
  join \
  <(coinboy list:funded-account-amounts ) \
  <(coinboy list:funded-account-prices )
}
get-value() {
  list | while read -r code amount price
  do
   echo -e "${code}\t$( get-balance )"
  done | sort | deflate
}
get-balance() {
  echo "scale=2; ${price} * ${amount}" | bc -l
}
_list-funded-account-balances() { 
  interface "cached-${FUNCNAME//_/}"
}
##################################################
_list-funded-account-balances ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
