#!/bin/bash
## portfolio-assets
## version 0.0.1 - initial
##################################################
shopt -s expand_aliases
alias bind-variables='
{
  local -r TEMP=$( mktemp )
  local delimiter=","
  local show_dialog="false"
  local copy_to_clipboard="false"
  local -i delay=300000
}
'
on-shortops-case() {
 case ${1} in
  f) {
   case ${2} in
    tsv) delimiter='\t' ;;
    csv|*) delimiter=',' ;;
   esac
   echo 2
  } ;;
  d) {
   show_dialog="true"
   echo 1
  } ;;
  c) {
   copy_to_clipboard="true"
   echo 1
  } ;;
  t) {
   delay="${2}"
   echo 2
  } ;;
  *) {
    true
  } ;;
 esac
}
output() {
  echo "$( get peg-diff ) ${code} ${amount} ${balance} ${peg} ${peg_diff}" \
  | tr ' ' "${delimiter}" 
}
cleanup() {
  test ! -f "${TEMP}" || rm -f "${_}"
  test ! -f "${TEMP}-convert" || rm -f "${_}"
}
dialog-wish() {
  local -x TK_SILENCE_DEPRECATION=1
  wish << EOF
proc sleep {time} {
  after \$time set end 1
  vwait end
}
label .disptitle -text "$( cat ${TEMP}-convert )"
button .prog -text "Convert to ALGO"
pack .disptitle .prog -fill both
sleep ${delay}
destroy .
EOF
}
dialog() {
  test ! "${show_dialog}" = "false" || { true ; return ; }
  test ! $( cat "${TEMP}-convert" | wc -l ) -eq 0 || { true ; return ; }
  ${FUNCNAME}-wish
}
filter() {
  gawk '{if($(5)>1) print}' -
}
payload() {
  {
    foreach-funded-account output \
    | sort -nr \
    | cut '-f2-' \
    | tee "${TEMP}" \
    | filter \
    | tee "${TEMP}-convert"
  }
  cat "${TEMP}"
}
copy-to-clipboard() {
  test ! "${copy_to_clipboard}" = "false" || { true ; return ; } 
  cat - | pbcopy
}
persist-last-balance() {
  . <(gawk '{print "store["tolower($(1))"-usd-last-balance]=\""$(3)"\""}' -)
}
_portfolio-assets() { 
  init-store-silent
  bind-variables
  getops "${@}"
  payload
  dialog
  copy-to-clipboard < ${TEMP}
  persist-last-balance < ${TEMP}
  cleanup
  store persist
}
##################################################
_portfolio-assets ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
