#!/bin/bash
## list-funded-accounts
## version 0.0.1 - initial
##################################################
purge-cache() {
  coinboy store:purge cached
}
rebuild-cache() {
  {
    coinboy list:funded-account-amounts # standalone
    coinboy list:funded-account-pegs # depends on amounts
    coinboy list:funded-account-prices # depends on amounts
    coinboy list:funded-account-balances  # depends on amounts and prices
    coinboy list:funded-account-peg-diffs # depends on balances and pegs
  } >/dev/null
}
join-lists() {
  join \
  <(join \
    <(join \
      <(join <(coinboy list:funded-account-amounts ) \
        <(coinboy list:funded-account-pegs)) \
        <(coinboy list:funded-account-prices)) \
    <(coinboy list:funded-account-balances)) \
  <(coinboy list:funded-account-peg-diffs) \
  | tr ' ' '\t'
}
_list-funded-accounts() { 
  purge-cache
  rebuild-cache
  join-lists
}
##################################################
_list-funded-accounts ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
