#!/bin/bash
## transactions-list
## version 0.0.1 - initial
##################################################
_transactions-list() { { local account_id ; account_id="${1}" ; }
  local timestamp=$( date +%s )
  local method="GET"
  local request_path
  case ${account_id} in 
   *starting_after*) request_path="${1}" ;;
   *) request_path="/v2/accounts/${account_id}/transactions" ;;
  esac
  local body=""
  local signature=$( echo -n "${timestamp}${method}${request_path}${body}" | openssl dgst -sha256 -hmac "${coinbase_api_secret}" )
  local res=$(
    curl "https://api.coinbase.com${request_path}" \
    -H "CB-ACCESS-KEY: ${coinbase_api_key}" \
    -H "CB-ACCESS-SIGN: ${signature}" \
    -H "CB-ACCESS-TIMESTAMP: ${timestamp}" \
    -H "CB-VERSION: 2021-03-20" \
    --silent
  )
  echo "${res}" | jq '.data[]'
  local next_uri=$( echo "${res}" | jq -r '.pagination.next_uri' )
  test ! "${next_uri}" != "null" || {
    ${FUNCNAME} "${next_uri}"
  }
}
##################################################
_transactions-list ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
