#!/bin/bash
## watch-crypto
## version 0.0.1 - initial
##################################################
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
list-crypto-filter() {
  grep -v -e 'USDC'
}
list-crypto() {
  coinboy list:funded-accounts | ${FUNCNAME}-filter | cut '-f1'
}
foreach-crypto() { { local function_name ; function_name="${1}" ; }
  local crypto
  for crypto in $( list-crypto )
  do
   "${function_name}"
  done
}
_watch-crypto() { 
  ## queue crypto price watch
   _() {
     cecho green "watching ${crypto}-${currency:-USD} price ..."
     coinboy watch:price ${crypto}-${currency:-USD}{,-${today}} ${delay:-60} &>/dev/null &
   }
   foreach-crypto _
   unset -f _
   # show realtime watch stats
   [  ] || { 
     while :
     do
      test ! -f "BTC-USD-${today:-yymmdd}" || { true ; break ; }
      echo -n "."
      sleep 1
     done
     tail -f *-USD-${today:-yymmdd}
   }
   wait
}
##################################################
_watch-crypto ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
