#!/bin/bash
## buys-list
## version 0.0.1 - initial
##################################################
shopt -s expand_aliases
alias bind-variables='
{
  local starting_after  
}
'
on-shortops-case() {
 case ${1} in
  s) {
   starting_after="${2}"
   echo 2
  } ;;
  *) {
    true
  } ;;
 esac
}
_buys-list() { { local account_id ; account_id="${1}" ; getops "${@:2}" ; }
  bind-variables
  test "${account_id}" || { error "false" ; cecho yellow "missing account id" ; false ; }
  local timestamp=$( date +%s )
  local method="GET"
  local request_path="/v2/accounts/${account_id}/buys" ;
  test ! "${starting_after}" || request_path="${request_path}?starting_after=${starting_after}"
  local body=""
  local signature=$( echo -n "${timestamp}${method}${request_path}${body}" | openssl dgst -sha256 -hmac "${coinbase_api_secret}" )
  local res=$(
    curl "https://api.coinbase.com${request_path}" \
    -H "CB-ACCESS-KEY: ${coinbase_api_key}" \
    -H "CB-ACCESS-SIGN: ${signature}" \
    -H "CB-ACCESS-TIMESTAMP: ${timestamp}" \
    -H "CB-VERSION: 2021-03-20" \
    --silent
  )
  echo "${res}" | jq '.'
  return 
  local next_uri=$( echo "${res}" | jq -r '.pagination.next_uri' )
  test ! "${next_uri}" != "null" || {
    ${FUNCNAME} "${next_uri}"
  }
}
##################################################
_buys-list ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
