#!/bin/bash
## portfolio-peg-total
## version 0.0.1 - initial
##################################################
_portfolio-peg-total() { 
  foreach-funded-account get-peg | sum
}
##################################################
_portfolio-peg-total ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
