#!/bin/bash
## store-env
## version 0.0.1 - initial
##################################################
help() { 
  cat << EOF
coinboy store:env
exports store to environment

USAGE
  Read store into environment and export
  . <(coinboy store:env)  

EOF
}
on-shortops-case() {
 case ${1} in
  h) {
   show_help="true"
   echo 1
  } ;;
  *) {
    true
  } ;;
 esac
}
_store-env() { { getops ${@} ; }
  test ! "${show_help:-false}" = "true" || { help ; return ; }
  local IFS=":"
  clipboy store:list | while read -r key value
  do
   key=${key^^} # a -> A
   key=${key//-/_} # - -> _
   value=${value/ /} # [ ] -> []
   echo declare -x STORE_${key^^}=${value/ /}
  done
}
##################################################
_store-env ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
