#!/bin/bash
## watch-price
## version 0.0.1 - initial
##################################################
_watch-price() { 
  local spot
  local buy 
  local sell
  local high
  local low
  local this
  local last
  local line
  local i
  local action
  local -i delay
  local -i grace_period
  local -ir GRACE_PERIOD_START=300
  delay=1
  grace_period=${GRACE_PERIOD_START}
  spot=$( coinboy prices:spot BTC-USD )
  high="${spot}"
  low="${spot}"
  while :
  do 
   spot=$( coinboy prices:spot BTC-USD )
   buy=$( coinboy prices:buy BTC-USD )
   sell=$( coinboy prices:sell BTC-USD )
   action=""
   test ! ${grace_period} -le 1 || {
     test ! ${spot/.*/} -gt ${high/.*/} || {
       action="SELL"
       high="${spot}"
       low="${spot}"
       grace_period=${GRACE_PERIOD_START}
     }
     test ! ${spot/.*/} -lt ${low/.*/} || {
       action="BUY"
       low="${spot}"
       grace_period=${GRACE_PERIOD_START}
     }
   }
   this="spot: ${spot}|buy: ${buy}|sell: ${sell}|low: ${low}|high: ${high}|${action}"
   line=""
   for i in $( seq 0 ${#this} )
   do
    this_c="${this:i:1}" 
    last_c="${last:i:1}"
    test ! "${this_c}" != "${last_c}" && {
      line="${line}${this_c}"
    true
    } || {
      line="${line}\e[41m${this_c}\e[0m"
    }
   done 
   test ! "${this}" != "${last}" || {
     test ! "${last}" != "" || {
       echo -e "${line//|/\\t}"
     }
     last="${this}"
   }
   sleep ${delay}
   test ! ${grace_period} -gt 1 || {
     let grace_period-=1
   }
  done
}
##################################################
_watch-price ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
