#!/bin/bash
## list-funded-account-amounts
## version 0.0.1 - initial
##################################################
list() {
  coinboy accounts:list
}
get-value() {
  list \
  | jq -r '
if 
  .currency.type == "crypto" and 
  ((.balance.amount | test("^0.0+$")) | not)
then
 .currency.code + "\t" + .balance.amount
else
 empty 
end
' \
  | sort | deflate
}
_list-funded-account-amounts() { 
  interface "cached-${FUNCNAME//_/}"
}
##################################################
_list-funded-account-amounts ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
