#!/bin/bash
## prices-buy
## version 0.0.2 - minimal
##################################################
_prices-buy() { { local currency_pair ; currency_pair="${1}" ; }
  _prices-type buy
}
##################################################
_prices-buy ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
