#!/bin/bash
## list-funded-account-peg-diffs
## version 0.0.1 - initial
##################################################
list() {
  join \
  <(coinboy list:funded-account-balances ) \
  <(coinboy list:funded-account-pegs )
}
get-value() {
  list | while read -r code balance peg
  do
   echo -e "${code}\t$( get-peg-diff )"
  done | sort | deflate
}
get-peg-diff() {
  echo "scale=2; ${balance} - ${peg:-${balance}}" | bc -l
}
_list-funded-account-peg-diffs() { 
  interface "cached-${FUNCNAME//_/}"
}
##################################################
_list-funded-account-peg-diffs ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on 
## see <https://github.com/temptemp3/sh2>
##################################################
