#!/bin/bash
## run-example-001-bash-declare-intenger-assignment
## version 0.0.1 - initial
##################################################
_run-example-001-bash-declare-intenger-assignment() {
  local var
  local empty_var
  local -i int
  ## assign int value without quote
  int=1
  cecho green "int=1"
  cecho yellow "${int}" # 1
  ## assign int value with quote
  int="2"
  cecho green "int=2"
  cecho yellow "${int}" # 2
  ## assign int value of another variable
  int=var
  cecho green "int=var"
  cecho yellow "${int}" # 0
  ## assign other variable value to int
  var=3
  cecho green "var=3"
  ## assign int value of another variable again
  int=var
  cecho green "int=var"
  cecho yellow "${int}" # 3
  ## assign int value of another variable w/ increment
  int=var+1
  cecho green "int=var+1"
  cecho yellow "${int}" # 4
  ## assign int value of another variable empty 
  int=empty_var
  cecho green "int=\"empty_var\""
  cecho yellow "${int}" # 0
  ## assign int value of another variable in quotes
  int="var"
  cecho green "int=\"var\""
  cecho yellow "${int}" # 3
  ## assign int value of another variable random
  int="RANDOM"
  cecho green "int=\"RANDOM\""
  cecho yellow "int: ${int}" # maybe 1234
}
##################################################
_run-example-001-bash-declare-intenger-assignment ${@}
##################################################
## generated by create-stub2.sh v0.1.2
## on
## see <https://github.com/temptemp3/sh2>
##################################################
